/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects and is checked in here
// so the repository type-checks immediately after install.
